### ISSUE TITLE
General cleanup

### ISSUE THREAD

**Issue by ofosos** [ofosos/ox-epub#11]
I want to clean up the codebase a little.

Ideally the auxilliary files would all be generated in org-epub--export-wrapper and not in the html template. So the generation would move to the export wrapper.

The org-epub-images would make way for another structure, which would be named org-epub-manifest. This structure would contain a list of alists which hold the information of how to generate the manifest (among them mimetype, linearness and id). This list should be used as the basis for generating the manifest and the content list as well as the spine. The corresponding functions will iterate over this list and pick the files that are relevant to their output file.

@pank what do you think?

**Comment by pank** [comment]
I hope I am able to address all aspects, but I don't understand neither the code structure nor epubs as well as you. 

> Ideally the auxilliary files would all be generated in org-epub--export-wrapper and not in the html template. So the generation would move to the export wrapper.

I agree that auxilliary files should probably not be part of `org-epub-template`.  To the extend it's feasible, it should generate the actual html file that is the book.

> The org-epub-images would make way for another structure, which would be named org-epub-manifest. This structure would contain a list of alists which hold the information of how to generate the manifest (among them mimetype, linearness and id).

I am not sure I understand here, and I don't see `org-epub-images` in the code, only the two `defvars`.  

Speaking of images, it might be nicer use `org-export-get-reference` to get an `id` rather than relying on a counter.  But I guess that can be discussed later (I'd have to have a closer look at the image code).

> The corresponding functions will iterate over this list and pick the files that are relevant to their output file.

Is your goal to find all files to be included in the final zip?

**Comment by ofosos** [comment]
Oh, this would be `org-epub-image-list`.

So instead there would be `org-epub-manifest`.

Basically I want a central list, that defines the type of each file (`:image`, `:stylesheet`, `:html`, `:cover-image`, `:cover-html`), it's id (presently done by hand or nameify), it's mime type (mostly guesswork at this stage). The relative order in this list will be preserved (to have the cover page in the front position). This simplify things, when we need to generate special/auxilliary files.

**Comment by pank** [comment]
Mark Meyer <notifications@github.com> writes:

> Oh, this would be `org-epub-image-list`.
>
> So instead there would be `org-epub-manifest`.
>
> Basically I want a central list, that defines the type of each file
> (`:image`, `:stylesheet`, `:html`, `:cover-image`, `:cover-html`),

This sounds like a mix between the info plist and the parse-tree
(org-element-parse-buffer).

> it's id (presently done by hand or nameify),

You can create a unique id of an element with org-export-get-reference.
They should already be there since you are using ox-html as a backend.

> it's mime type (mostly guesswork at this stage). The relative order in
> this list will be preserved (to have the cover page in the front
> position).

The order should already be in order in the parse-tree.

> This simplify things, when we need to generate special/auxilliary files.

-- 
Evidence suggests Snowden used a powerful tool called monospaced fonts

**Comment by ofosos** [comment]
>>>>> pank  <notifications@github.com> writes:

    > I agree that auxilliary files should probably not be part of
    > org-epub-template. To the extend it's feasible, it should generate
    > the actual html file that is the book.

The org file includes most of the metadata, this means we'll have to
fill in a dynamic variable that holds this metadata during html
generation and then pass this on to the file generation functions.

    > Speaking of images, it might be nicer use org-export-get-reference
    > to get an id rather than relying on a counter. But I guess that
    > can be discussed later (I'd have to have a closer look at the
    > image code).

Yep, for images this is definitely the best way to do it. I'm already
using org-export-get-reference to reference the headlines. But since
every content file need to have an id assigned, I'd stick with nameify
for this.

Cheers, Mark


-- 
   Mark Meyer
   mark@ofosos.org

**Comment by ofosos** [comment]
>>>>> pank  <notifications@github.com> writes:

> Mark Meyer <notifications@github.com> writes:
>> Oh, this would be `org-epub-image-list`.
>> 
>> So instead there would be `org-epub-manifest`.
>> 
>> Basically I want a central list, that defines the type of each
>> file (`:image`, `:stylesheet`, `:html`, `:cover-image`,
>> `:cover-html`),

> This sounds like a mix between the info plist and the parse-tree
> (org-element-parse-buffer).

I'll look into `org-element-parse-buffer`.

>> it's mime type (mostly guesswork at this stage). The relative
>> order in this list will be preserved (to have the cover page in
>> the front position).

> The order should already be in order in the parse-tree.

The cover page generally requires special processing to be completely
visible, hence the document property that specifies the cover
image. It might be desirable to let a user design a html cover page, but
this won't appear as an icon on most readers.

Cheers, Mark
-- 
   Mark Meyer
   mark@ofosos.org

**Comment by pank** [comment]
Mark Meyer <notifications@github.com> writes:

> I'll look into `org-element-parse-buffer`.

When exporting it, you have it available as

    (plist-get info :parse-tree)

When experimenting in buffers, you can use (org-element-parse-buffer)
e.g. for org-element-map.

-- 
Lasciate ogni speranza o voi che entrate: siete nella mani di'machellaio

**Comment by ofosos** [comment]
Most of the cleanup is done. File generation moved to `org-epub--export-wrapper` and copying moved to `org-epub-zip-it-up`.

Now what's needed? 
- I think it's necessary to catch conditions that arise duing export, and properly delete all temp files/directories
- I think the buffer operations in `org-epub--export-wrapper` might need some work

Cheers, Mark

**Comment by ofosos** [comment]
condition-case is in

@pank I'll be looking at the parse tree, do you have any other issues that need to be addressed?
