### ISSUE TITLE
Add elisp hook to export menu

### ISSUE THREAD

**Issue by ofosos** [ofosos/ox-epub#12]
Add elisp hook to export menu. I.e. when you export something you can place an elisp snippet in a custom variable that then get's executed with the new epub filename as a parameter.

**Comment by pank** [comment]
I think similar functions are already built in?  I'd guess mostly anything can be done via `org-export-filter-parse-tree-functions`, `org-export-filter-*-functions`, `org-export-before-processing-hook`, and `org-export-before-parsing-hook`.
