### ISSUE TITLE
Export doesn't work

### ISSUE THREAD

**Issue by rmattes** [ofosos/ox-epub#13]
Hello, when I try to export an org file the export stops with the following error:

```elisp
ox-epub eport error: (file-missing Setting current directory No such file or directory /tmp/user/1000/epub-24423_1l/META-INF/)
```
The `*Messages*` buffer contains:

```
org-babel-exp process clojure at position 67857...
org-babel-exp process clojure at position 68076...
Created wiki link.
Created wiki-asset-sys link.
(New file)
Saving file /tmp/user/1000/epub-24423_1l/style.css...
Wrote /tmp/user/1000/epub-24423_1l/style.css
Use M-x make-directory RET RET to create the directory and its parents
Using vacuous schema
ox-epub eport error: (file-missing Setting current directory No such file or directory /tmp/user/1000/epub-24423_1l/META-INF/)
```

Thanks, Ralf Mattes

**Comment by ofosos** [comment]
Hey Ralf,
what Emacs version are you using? Will be looking into this 1800Z today.

**Comment by rmattes** [comment]
Oh, sorry, I'm using GNU Emacs 26.0.50 (deployed as emacs-snapshot in Debian testing)

**Comment by ofosos** [comment]
Hey Ralf, can you try 0.2.2. This might fix your issue.

**Comment by rmattes** [comment]
No - unfortunately not. First it breaks with `not enough arguments in format string`.
This here seems to be wrong:
```
(format
          "<h1 class=\"title\">%s%Es</h1>\n")
```

After fixing this I still get this:
```
ox-epub eport error: (file-error Setting current directory No such file or directory /tmp/user/1000/epub-30902UkF/META-INF/)
```

I don't understand your code here:
```
(with-current-buffer (find-file (concat org-epub-zip-dir "META-INF/container.xml"))
  (erase-buffer)
  (insert (org-epub-template-container))
  (unless (file-exists-p (expand-file-name "META-INF" org-epub-zip-dir))
    (make-directory (expand-file-name "META-INF" org-epub-zip-dir)))
  (save-buffer 0)
  (kill-buffer))
```
Aren't you trying to find-fle a file in a directory that doesn't yet exist?

**Comment by ofosos** [comment]
Yep, I'm using find-file before actually creating that directory. I'm currently compiling emacs 26 to what this is about. The `META-INF` directory is not being created, maybe this is due to the fact that `META-INF` does not have a trailing slash in the code, but I'm not sure. It works on emacs 24/25 on linux.

**Comment by ofosos** [comment]
Now running emacs 27 from git. I don't have the problem. But I pushed a change to master that would ensure that we're always passing a dirname to make-directory, this should not be needed, but then the documentation kind of hints at the fact that it is required.

Can you try pulling from master? Just downloading the file and doing evaluate-buffer should be sufficient, then export with `C-c C-e E e`.

**Comment by ofosos** [comment]
Can you try if the current release fixes this? At least the format string error should be gone and maybe the file error.

**Comment by rmattes** [comment]
Yes, my (rather elaborate) testcase exports without problems. Thank's a lot!
