### ISSUE TITLE
Export fails with error: Non-regular file is a directory

### ISSUE THREAD

**Issue by rjekker** [ofosos/ox-epub#15]
Hi,

My export fails with the following error:

ox-epub eport error: (file-error Non-regular file is a directory /home/reindert/org/courses)

a full listing of the output is here:

```
org-babel-exp process elisp at position 697...
org-babel-exp process python at position 4695...
(this message repeats a couple hundred times)
org-babel-exp process python at position 191328...
org-babel-exp process python at position 192623...
Can't guess python-indent-offset, using defaults: 4 [12 times]
Using schema /usr/share/emacs/24.5/etc/schema/xhtml.rnc
(New file)
Saving file /tmp/epub-12881bRM/style.css...
Wrote /tmp/.!tmp!epub-12881bRM!style.css.~undo-tree~
Wrote /tmp/epub-12881bRM/style.css
Use M-x make-directory RET RET to create the directory and its parents
Using vacuous schema
Saving file /tmp/epub-12881bRM/META-INF/container.xml...
Wrote /tmp/.!tmp!epub-12881bRM!META-INF!container.xml.~undo-tree~
Wrote /tmp/epub-12881bRM/META-INF/container.xml
(New file)
Saving file /tmp/epub-12881bRM/mimetype...
Wrote /tmp/.!tmp!epub-12881bRM!mimetype.~undo-tree~
Wrote /tmp/epub-12881bRM/mimetype
(New file)
Saving file /tmp/epub-12881bRM/body.html...
Wrote /tmp/.!tmp!epub-12881bRM!body.html.~undo-tree~
Wrote /tmp/epub-12881bRM/body.html
(New file)
Saving file /tmp/epub-12881bRM/toc.ncx...
Wrote /tmp/.!tmp!epub-12881bRM!toc.ncx.~undo-tree~
Wrote /tmp/epub-12881bRM/toc.ncx
(New file)
Saving file /tmp/epub-12881bRM/content.opf...
Wrote /tmp/.!tmp!epub-12881bRM!content.opf.~undo-tree~
Wrote /tmp/epub-12881bRM/content.opf
ox-epub eport error: (file-error Non-regular file is a directory /home/reindert/org/courses)
```

I use the following emacs/org versions:

Org mode version 9.1.1 
GNU Emacs 24.5.1 (x86_64-pc-linux-gnu, X toolkit, Xaw3d scroll bars) of 2017-09-20 on lcy01-07, modified by Debian

**Comment by ofosos** [comment]
Can you provide some details on how you trigger the export?

**Comment by ofosos** [comment]
Are you trying a subtree export?

**Comment by rjekker** [comment]
I'm exporting by doing M-x org-epub-export-to-epub.

Tested this on my Mac as well, and got the same problem, with following versions:

Org mode version 9.1.2 (9.1.2-15-g1d5142-elpa @ /Users/reindert/.emacs.d/elpa/org-20171016/)
GNU Emacs 25.3.1 (x86_64-apple-darwin13.4.0, NS appkit-1265.21 Version 10.9.5 (Build 13F1911)) of 2017-09-12

To test whether it was something in my org file, I tried the file below, which gave the same error:

```
#+TITLE: test
#+DATE: 2017
#+AUTHOR: rjekker

* Test epub export

A line

** Sublevel heading

Another bit of text

```

**Comment by rjekker** [comment]
A short update- hope it will help you track down the error - I just tried the last version from git -- [this one](https://github.com/ofosos/ox-epub/commit/c12467d1c6a2a3f89e1e271c44e29eb5409ed9df) -- and interestingly it gave another error: "Not enough arguments for format string", which I tracked down to line 295:

`(format "<h1 class=\"title\">%s%Es</h1>\n")`

After removing the `%s%Es` part from this line it unfortunately goes back to the old error: `ox-epub eport error: (file-error Non-regular file Is a directory /Users/...)`

Strangely, using debug-on-error does not trigger a debug session when this error occurs.. any suggestions?

**Comment by rjekker** [comment]
Ok.. I tracked it down to this: the error occurs in the first mapc statement in `org-epub-zip-it-up`.
But before that gets called, another piece of code already causes this message: "Use M-x make-directory RET RET to create the directory and its parents", which seems weird to me.

That's all the info I have right now.. hope you can solve this problem, would really love to be able to export to epub!

**Comment by rjekker** [comment]
Ok.. one more debugging session later.. org-epub-zip-it-up gets called with the following `files` argument:

`((:id "default-style" :filename "style.css" :type stylesheet :mimetype "text/css" :source nil) (:id "style-1" :filename "style-1.css" :type stylesheet :mimetype "text/css" :source "") (:id "body-html" :filename "body.html" :type html :mimetype "application/xhtml+xml" :source nil))`

When, in the mapc, the `org-epub-manifest-needcopy` function gets called for style-1.css, it returns the value `("" . "style-1.css")`

You are calling `copy-file` with a first argument of `(car copy)`, which evaluates to the empty string, meaning the current working directory, and that seems to cause the error.

**Comment by rjekker** [comment]
I now changed the mapc in org-epub-zip-it-up like this, so that it checks for the empty string:

```
  (mapc #'(lambda (entry)
	    (let ((copy (org-epub-manifest-needcopy entry)))
	      (when (and copy (not (string= "" (car copy))))
                (copy-file (car copy) (concat target-dir (cdr copy)) t))))
```

This seems to work for me. I don't really know about epubs and what should be in the manifest, so I really don't know if this fix is acceptable at all.

Also, this leaves a minor bug: the export still gives the message "Use M-x make-directory RET RET to create the directory and its parents"

**Comment by ofosos** [comment]
I wouldn't consider this message a bug, it's rather noisy. I think I fixed the format string in master. I'm now looking into mapc.

**Comment by ofosos** [comment]
Ok, it looks like something is broken with the parsing of EPUBSTYLE property, which I assume you define.

Can you please send a test file that triggers this behaviour? Basically the `source` property of this element should never be "", if it is it needs to be caught beforehand.

**Comment by rjekker** [comment]
The file that causes this behaviour is included in [this comment](https://github.com/ofosos/ox-epub/issues/15#issuecomment-338308216), there's not really anything special in there. I did not set any property besides author/title/date. Is there any other way that this style property might be set, through another org-mode setting perhaps?

**Comment by rjekker** [comment]
The error in the format string seems to be fixed though, thanks :)

**Comment by ofosos** [comment]
In line 240 can you try replacing `org-split-string` with `split-string`?

**Comment by ofosos** [comment]
Nope, that won't work. Wait a second.

**Comment by rjekker** [comment]
Actually, it does work!

**Comment by rjekker** [comment]
Could it be that htmlize - which I use for source code blocks - causes this?

**Comment by ofosos** [comment]
Can you pull and test if this now fixes the issues? I added some more stuff to be more robust in there. When org mode now return an empty string for the EPUBSTYLE property, it'll still work. And it's switched to string-split. I'm not sure, org-split-string moved around files during development, I did not check out a newer version of org mode to see if this is really the culprit, but I also think the code is wrong and it should be this way.

**Comment by rjekker** [comment]
Yes, this works! Thanks for reacting so quickly :)

**Comment by ofosos** [comment]
Dang. `(org-split-string "")` return `nil` for my copy of org mode, but the current upstream will return `("")`, so we switch to `split-string`, which does the right thing and should be more stable. I have to look into what this does to compatibility.

**Comment by ofosos** [comment]
Ok, looks good. I'm cutting a new release and after that it's a homebrew for me. Thanks for the good work. I reverted one change and switched it simply to `split-string`, which as an Emacs function should be compatible into the foreseeable future.
