### ISSUE TITLE
7-zip failing. package not using archive-zip-update value

### ISSUE THREAD

**Issue by web43037** [ofosos/ox-epub#19]
Hi, I use emacs on Windows 10 and my zip program of choice is 7-zip. 

I used the customization  feature to set the archive-zip-update variable but it appears that it is not being used by ox-epub. I am _requesting_ that your group provides support for 7-zip and the archive-zip-update variable.

I don't know how to program in elisp, but got digging around and see that the function 'org-epub-zip-it-up' has hard-coded the process to call as "zip" and so it looks like any changes I make in my customization will not be picked up.

The customization lets me declare the program used to update an archive with files. In my case it is:  
-  C:\Program Files\7-Zip\7z.exe. 
Notice there is a space in the name so don't forget to handle that.

I can also set the option needed for update and in the case of 7-zip it is 'a'. Here is an example of a working command, after changing to the directory of interest: 
- dir-location> "C:\Program Files\7-Zip\7z.exe" a junk.zip *.

This picks up all the files where I was and adds them to junk.zip.

If I read your code right, you are using "-Xu0" or "-Xu9" for some option on the "zip" command. I don't know what those do or the corollary for 7-zip. Here is the site 7-zip: http://www.7-zip.org/.

I dumped the options using the help switch and get this cryptic list of 7-zip options.
-  [7-zip-options.txt](https://github.com/ofosos/ox-epub/files/1436319/7-zip-options.txt)

The project is on Sourceforge and supposedly support is here, but a description of the options is not readily apparent:

-  https://sourceforge.net/p/sevenzip/discussion/45797

So I don't know how your review, code change and notification process works on Github so a post to my email would be nice: luthycraig@gmail.com. I would like to get playing with this package by Sunday (5nov) if possible. I know everybody wants their fix right now, so whatever fits your schedule, please let me know what to expect.

Thanks,
Craig

**Comment by ofosos** [comment]
Zip is partly an archive format and partly a compression format. These options prevent compression of the initial file in the archive, which is required by the Epub standard.

I can change the path to the zip utility to be dynamic, but you may want to use something different from 7zip, apparently it doesn't have an option to set compression ratio of single files.

**Comment by web43037** [comment]
Hi,

I cannot seem to find the zip.exe that is current on Win 10. So, digging a little deeper I found a way to add a file to an archive without compression and then add files with compression. Here is the example done on the command line:

### POTENTIAL SOLUTION
C:\temp>cd 7z-rhb

C:\temp\7z-rhb>dir /b    **<<== a folder with 4 files**
7-zip-options.txt
first_pages.html
second_pages.html
Symbol Key Synopsis_exported_2015-02-01-132822.html

C:\temp\7z-rhb>7z a -mx0 -tzip junk.zip 7-zip-options.txt  **<<== command line, no compression**

7-Zip [64] 16.04 : Copyright (c) 1999-2016 Igor Pavlov : 2016-10-04

Scanning the drive:
1 file, 2630 bytes (3 KiB)

Creating archive: junk.zip

Items to compress: 1

Files read from disk: 1
Archive size: 2798 bytes (3 KiB)
Everything is Ok

C:\temp\7z-rhb>7z a -mx5 -tzip junk.zip *.html  **<<== command for normal compression**

7-Zip [64] 16.04 : Copyright (c) 1999-2016 Igor Pavlov : 2016-10-04

Open archive: junk.zip

Path = junk.zip
Type = zip
Physical Size = 2798

Scanning the drive:
3 files, 171393 bytes (168 KiB)

Updating archive: junk.zip

Items to compress: 3

Files read from disk: 3
Archive size: 38426 bytes (38 KiB)
Everything is Ok

### DISCUSSION

- 'a -mx0 -tzip' are the options to add the file to a ZIP archive with no compression

- 'a -mx5 -tzip' are the options to add the file to a ZIP archive with "normal" compression. 7z has 5 compression levels. These are 0, 1, 3, 5, 7 and 9. It appears similar to your use of -Xu9 and -Xu0.

Here is what they mean if creating a ZIP archive:
![compression-levels](https://user-images.githubusercontent.com/5453248/32354211-b94edbd6-bff6-11e7-9ecb-fd87a85483bd.PNG)

I guess for this to work for customization one would need the option string for no compression and for maximum compression. 7z throws in a little wrinkle for options because the command line includes the command and the switches.

Commands are extensive and the switches even worse.

Command | Description
-- | --
a | Add
b | Benchmark
d | Delete
e | Extract
h | Hash
i | Show information about supported formats
l | List
rn | Rename
t | Test
u | Update
x | eXtract with full paths

### THE QUESTION:
Is there enough here to warrant making your code pick up the zip executable and no-compression and maximum-compression options? It would make your routine a little more robust. However, I am also comfortable with hard coding these values in my own copy of your code. I just don't know what I might break. Is the org-epub-zip-it-up the only function that needs to change?

Unfortunately I have no experience programming with emacs or elisp and not a lot of interest in starting. Thanks for your time and help.

**Comment by ofosos** [comment]
I think this should be in the code by default, I can add it in the evening (now on UTC+1).

So we'll need two customization options, one for `no compress` and one for `compress` and each needs a way to replace the target and source filename, so that we can account for zip files that switch the order of these arguments around.

**Comment by web43037** [comment]
OK. Thanks a bunch. I am on Chicago time. UTC-5.

**Comment by ofosos** [comment]
Hey ho, good morning :)

Can you give the `master` branch a spin? I think you know how to handle redifining these variable without me providing a customization facility.

**Comment by ofosos** [comment]
Hmm, if you're using 7zip you also need to make sure that it's generating plain old zip files. I don't think epub readers will work if these are in 7zip format.

**Comment by ofosos** [comment]
Wait, doing some more changes.

**Comment by ofosos** [comment]
Now you should be able to do something like this in your emacs init file:
```(setq org-epub-zip-command "c:\foobar'7zip")
(setq org-epub-zip-no-compress (list "-mx0" "-tzip"))
(setq org-epub-zip-compress (list "-mx5" "-tzip"))
```

**Comment by web43037** [comment]
the -tzip option tells 7zip what kind of archive to create. It will make a number of them.
I am going to work with your work today (and this week).

**Comment by web43037** [comment]
Not having success. I was not sure how to get the master branch, so just copied and pasted ox-epub.el from Github to my local copy and deleted the .elc file. Would this work? Note that there is a space in the option set for compression. Could embedded spaces be the culprit? Ran 2 tests with slightly different setttings.

## TEST1
### This is what I added to init.el. 
(setq org-epub-zip-command "7z")
(setq org-epub-zip-no-compress (list **"a -mx0"** "-tzip"))
(setq org-epub-zip-compress (list **"a -mx5"** "-tzip"))

### These are the messages. Started emacs fresh for this run.
Loading linum...done
Loading ido...done
Getting Started.pdf has auto save data; consider M-x recover-this-file
Composing main Info directory...done
Composing main Info directory...done
Wrote c:/Users/dad/Dropbox/.emacs.d/.emacs.desktop.lock
Desktop: 1 frame, 24 buffers restored.
For information about GNU Emacs and the GNU system, type C-h C-a.
Debug (ox-odt): Searching for OpenDocument styles files...
Debug (ox-odt): Trying c:/usr/share/emacs/etc/org/styles/... [2 times]
Debug (ox-odt): Trying c:/Users/dad/Dropbox/.emacs.d/elpa/etc/styles/...
Debug (ox-odt): Trying c:/Users/dad/Dropbox/.emacs.d/elpa/org-20161003/etc/styles/...
Debug (ox-odt): Using styles under c:/Users/dad/Dropbox/.emacs.d/elpa/org-20161003/etc/styles/
Debug (ox-odt): Searching for OpenDocument schema files...
Debug (ox-odt): Trying c:/usr/share/emacs/etc/org/schema/... [2 times]
Debug (ox-odt): No OpenDocument schema files installed
Output to:
./Symbol_Key_Synopsis.epub
Transcription of Robert Heber Beesley Mission Journal
(New file)
Saving file c:/Users/dad/AppData/Local/Temp/epub-11808s1u/style.css...
Wrote c:/Users/dad/AppData/Local/Temp/epub-11808s1u/style.css
(New file)
Using vacuous schema
Saving file c:/Users/dad/AppData/Local/Temp/epub-11808s1u/META-INF/container.xml...
Wrote c:/Users/dad/AppData/Local/Temp/epub-11808s1u/META-INF/container.xml
(New file)
Saving file c:/Users/dad/AppData/Local/Temp/epub-11808s1u/mimetype...
Wrote c:/Users/dad/AppData/Local/Temp/epub-11808s1u/mimetype
(New file)
Saving file c:/Users/dad/AppData/Local/Temp/epub-11808s1u/body.html...
Wrote c:/Users/dad/AppData/Local/Temp/epub-11808s1u/body.html
(New file)
Saving file c:/Users/dad/AppData/Local/Temp/epub-11808s1u/toc.ncx...
Wrote c:/Users/dad/AppData/Local/Temp/epub-11808s1u/toc.ncx
(New file)
Saving file c:/Users/dad/AppData/Local/Temp/epub-11808s1u/content.opf...
Wrote c:/Users/dad/AppData/Local/Temp/epub-11808s1u/content.opf
ox-epub eport error: (file-error Copying file No such file or directory c:/Users/dad/AppData/Local/Temp/epub-11808s1u/Symbol_Key_Synopsis.epub c:/Users/dad/Dropbox/projects/+RHB_Missionary_Journal_Transcription/org/Symbol_Key_Synopsis.epub)
Loading linum...done
Loading ido...done
Getting Started.pdf has auto save data; consider M-x recover-this-file
Composing main Info directory...done
Composing main Info directory...done
Wrote c:/Users/dad/Dropbox/.emacs.d/.emacs.desktop.lock
Desktop: 1 frame, 24 buffers restored.
For information about GNU Emacs and the GNU system, type C-h C-a.
Debug (ox-odt): Searching for OpenDocument styles files...
Debug (ox-odt): Trying c:/usr/share/emacs/etc/org/styles/... [2 times]
Debug (ox-odt): Trying c:/Users/dad/Dropbox/.emacs.d/elpa/etc/styles/...
Debug (ox-odt): Trying c:/Users/dad/Dropbox/.emacs.d/elpa/org-20161003/etc/styles/...
Debug (ox-odt): Using styles under c:/Users/dad/Dropbox/.emacs.d/elpa/org-20161003/etc/styles/
Debug (ox-odt): Searching for OpenDocument schema files...
Debug (ox-odt): Trying c:/usr/share/emacs/etc/org/schema/... [2 times]
Debug (ox-odt): No OpenDocument schema files installed
Output to:
./Symbol_Key_Synopsis.epub
Transcription of Robert Heber Beesley Mission Journal
(New file)
Saving file c:/Users/dad/AppData/Local/Temp/epub-11808s1u/style.css...
Wrote c:/Users/dad/AppData/Local/Temp/epub-11808s1u/style.css
(New file)
Using vacuous schema
Saving file c:/Users/dad/AppData/Local/Temp/epub-11808s1u/META-INF/container.xml...
Wrote c:/Users/dad/AppData/Local/Temp/epub-11808s1u/META-INF/container.xml
(New file)
Saving file c:/Users/dad/AppData/Local/Temp/epub-11808s1u/mimetype...
Wrote c:/Users/dad/AppData/Local/Temp/epub-11808s1u/mimetype
(New file)
Saving file c:/Users/dad/AppData/Local/Temp/epub-11808s1u/body.html...
Wrote c:/Users/dad/AppData/Local/Temp/epub-11808s1u/body.html
(New file)
Saving file c:/Users/dad/AppData/Local/Temp/epub-11808s1u/toc.ncx...
Wrote c:/Users/dad/AppData/Local/Temp/epub-11808s1u/toc.ncx
(New file)
Saving file c:/Users/dad/AppData/Local/Temp/epub-11808s1u/content.opf...
Wrote c:/Users/dad/AppData/Local/Temp/epub-11808s1u/content.opf
ox-epub eport error: (file-error Copying file No such file or directory c:/Users/dad/AppData/Local/Temp/epub-11808s1u/Symbol_Key_Synopsis.epub c:/Users/dad/Dropbox/projects/+RHB_Missionary_Journal_Transcription/org/Symbol_Key_Synopsis.epub)

## TEST 2
### init.el settings
(setq org-epub-zip-command "C:\Program Files\7-Zip\7z.exe")
(setq org-epub-zip-no-compress (list "a -mx0" "-tzip"))
(setq org-epub-zip-compress (list "a -mx5" "-tzip"))

### Messages
Loading linum...done
Loading ido...done
Getting Started.pdf has auto save data; consider M-x recover-this-file
Composing main Info directory...done
Composing main Info directory...done
Wrote c:/Users/dad/Dropbox/.emacs.d/.emacs.desktop.lock
Desktop: 1 frame, 28 buffers restored.
For information about GNU Emacs and the GNU system, type C-h C-a.
Debug (ox-odt): Searching for OpenDocument styles files...
Debug (ox-odt): Trying c:/usr/share/emacs/etc/org/styles/... [2 times]
Debug (ox-odt): Trying c:/Users/dad/Dropbox/.emacs.d/elpa/etc/styles/...
Debug (ox-odt): Trying c:/Users/dad/Dropbox/.emacs.d/elpa/org-20161003/etc/styles/...
Debug (ox-odt): Using styles under c:/Users/dad/Dropbox/.emacs.d/elpa/org-20161003/etc/styles/
Debug (ox-odt): Searching for OpenDocument schema files...
Debug (ox-odt): Trying c:/usr/share/emacs/etc/org/schema/... [2 times]
Debug (ox-odt): No OpenDocument schema files installed
Output to:
./Symbol_Key_Synopsis.epub
Transcription of Robert Heber Beesley Mission Journal
(New file)
Saving file c:/Users/dad/AppData/Local/Temp/epub-2556KHv/style.css...
Wrote c:/Users/dad/AppData/Local/Temp/epub-2556KHv/style.css
(New file)
Using vacuous schema
Saving file c:/Users/dad/AppData/Local/Temp/epub-2556KHv/META-INF/container.xml...
Wrote c:/Users/dad/AppData/Local/Temp/epub-2556KHv/META-INF/container.xml
(New file)
Saving file c:/Users/dad/AppData/Local/Temp/epub-2556KHv/mimetype...
Wrote c:/Users/dad/AppData/Local/Temp/epub-2556KHv/mimetype
(New file)
Saving file c:/Users/dad/AppData/Local/Temp/epub-2556KHv/body.html...
Wrote c:/Users/dad/AppData/Local/Temp/epub-2556KHv/body.html
(New file)
Saving file c:/Users/dad/AppData/Local/Temp/epub-2556KHv/toc.ncx...
Wrote c:/Users/dad/AppData/Local/Temp/epub-2556KHv/toc.ncx
(New file)
Saving file c:/Users/dad/AppData/Local/Temp/epub-2556KHv/content.opf...
Wrote c:/Users/dad/AppData/Local/Temp/epub-2556KHv/content.opf
ox-epub eport error: (file-error Searching for program No such file or directory C:Program Files-Zipz.exe)
Loading c:/Users/dad/Dropbox/.emacs.d/recentf...done
Cleaning up the recentf list...done (0 removed)
Mark set
mwheel-scroll: End of buffer

**Comment by ofosos** [comment]
Hey, try passing every command line option as a seperate string so (list "a" "-mx0" "-tzip") and escaping the 7z path if you use the full path, i.e. "c:\\foo\\bar", compare http://www.gnu.org/software/emacs/manual/html_node/elisp/Syntax-for-Strings.html

**Comment by web43037** [comment]
Fantastic! It actually produced an .epub file! It is a bit late but I will give you a fuller report later. This is a one pager with no images.

**Comment by ofosos** [comment]
Do you still want to share some feedback, or should I go ahead and close this issue?

Anyway, I'm glad it works for you :)

**Comment by web43037** [comment]
Thanks - **this issue can be closed**. Seems to work fine. However, I don't know how to include the images. I have JPEG images in a neighboring folder. In my ORG file I reference these with a relative link. There are a **lot** of them. What is the magic here?

**Comment by ofosos** [comment]
Hey,
you can embed them as an image, then it should include them in the output.

Cheers, Mark

**Comment by web43037** [comment]
OK. Thanks again.
