### ISSUE TITLE
Perhaps this should be part of Org?

### ISSUE THREAD

**Issue by pank** [ofosos/ox-epub#2]
Hi,

This seems like this could be a very useful export backend.
It might be handy to make this part of Org so that it's available out of the box.

Note that you'd have to assign the copyright to FSF, which might require to fill out some paperwork.

The details are [here](http://orgmode.org/worg/org-contribute.html).

Thanks,
Rasmus

**Comment by ofosos** [comment]
With the exception of the zip code, it certainly fits in well with the org-mode code. I don't have any problems with contributing this to org-mode directly. I'm definitely open to the idea.

I think the FSF accepts signed papers from Germany and I assume they've done the legal work to establish that this holds up in a German court. I think in the past there were problems with the fact that "copyright assignment" does not exist in Germany. 

How do we proceed on this?

**Comment by pank** [comment]
Mark Meyer <notifications@github.com> writes:

> With the exception of the zip code, it certainly fits in well with the
> org-mode code.

Zip the program?  AFAIR that’s also what ox-odt.el does.  There’s no
problem with zipping stuff up.

> I don't have any problems with contributing this to org-mode
> directly. I'm definitely open to the idea.

Thanks.

> I think the FSF accepts signed papers from Germany and I assume
> they've done the legal work to establish that this holds up in a
> German court. I think in the past there were problems with the fact
> that "copyright assignment" does not exist in Germany.

I don't know.  The copyright clerk will know the details and can be
reached at assign@fsf.org.  It seems a scanned pdf is sufficient from
German citizens, so I don’t think there is a worry in this regard.

    https://www.fsf.org/blogs/licensing/fsf-to-begin-accepting-scanned-assignments-from-germany

> How do we proceed on this?

Please contact the copyright clerk get started with the copyright
assignment.  They should send you a pdf that you can sign and post or sign
electronically (presumably).

Please write an email about ox-epub.el to the org-mode mailing list.

    http://orgmode.org/community.html
    http://orgmode.org/worg/org-contribute.html

Thanks,
Rasmus

-- 
m-mm-mmm-mmmm bacon!

**Comment by ofosos** [comment]
Hi Rasmus,
I sent an email to the GNU project and requested the form, I also sent an email to the org-mode mailing list. I think we'll keep this bug until there's a decision as to the inclusion of ox-epub in org-mode.

Cheers, Mark

**Comment by ofosos** [comment]
Got the paperwork, it's on its way.

**Comment by ofosos** [comment]
As per the copyright clerk, the paperwork has been completed.

**Comment by ofosos** [comment]
Can be part of Emacs anytime. Paperwork done. No more work to do here.
