### ISSUE TITLE
I can't view the output with nov-mode

### ISSUE THREAD

**Issue by FrancescoCadei** [ofosos/ox-epub#23]
I can't view the ox-epub output with `nov-mode`, but I can view other epubs regulary.

My setting in `ox-pub`:
```elisp
 (add-to-list 'org-export-backends 'epub)
```

My settings in `nov-mode`:
```elisp
(add-to-list 'auto-mode-alist '("\\.epub\\'" . nov-mode))
(custom-set-faces '(variable-pitch ((t (:height 1.15)))))
```

org version: 9.1.14
emacs version: 25.1.1
platform: Debian 9
installed via: MELPA

**Comment by ofosos** [comment]
I'll look into this on the weekend.

**Comment by ofosos** [comment]
Can you try exporting the `epub` directly with `C-c C-e E e`? That should work. Defining ox-epub as a backend will usually not work, because it ties the exported files into a single epub in a separate function.

**Comment by FrancescoCadei** [comment]
To use `C-c C-e E e` I have to define ox-epub as backend.

**Comment by ofosos** [comment]
You're right.

Ok, I can reproduce this issue. Please add a stanza like this to your `org` file.
```
#+UID: http://ofosos.org/epub/sample.org
```

I will update the documentation accordingly.
