### ISSUE TITLE
Does not support export some kind of inline images

### ISSUE THREAD

**Issue by stardiviner** [ofosos/ox-epub#24]
```org
#+ATTR_ORG: :width 600
#+ATTR_LATEX: :width 6.0in
#+ATTR_HTML: :width 600px
[[file:data/4f/19eb7e-a943-477c-835b-d7df100e19ca/Clojure%20type%20selection%20flowchart.png]]
```
I have upper inline image, ox-epub report error:
```
ox-epub eport error: (file-missing Opening input file No such file or directory /home/stardiviner/Org/Wiki/Computer Technology/Programming/Programming Languages/Clojure/Data/Manuals/My Clojure Language Syntax Reference/data/4f/19eb7e-a943-477c-835b-d7df100e19ca/Clojure%20type%20selection%20flowchart.png)
user-error: No such file: /home/stardiviner/Org/Wiki/Computer Technology/Programming/Programming Languages/Clojure/Data/Manuals/My Clojure Language Syntax Reference/ox-epub eport error: (file-missing Opening input file No such file or directory /home/stardiviner/Org/Wiki/Computer Technology/Programming/Programming Languages/Clojure/Data/Manuals/My Clojure Language Syntax Reference/data/4f/19eb7e-a943-477c-835b-d7df100e19ca/Clojure%20type%20selection%20flowchart.png)
```

But the file exist.

Some inline images export fine, like this:
```org
#+ATTR_ORG: :width 500
#+ATTR_LATEX: :width 5.0in
#+ATTR_HTML: :width 500px
[[file:data/7d/d837d0-0489-4e45-be21-c332e1c6307d/threading%20flow%201.png][threading flow 1.png]]

#+ATTR_ORG: :width 500
#+ATTR_LATEX: :width 5.0in
#+ATTR_HTML: :width 500px
[[file:data/7d/d837d0-0489-4e45-be21-c332e1c6307d/threading%20flow%202.png][threading flow 2.png]]
```
Seems must have inline image description part.

![image](https://user-images.githubusercontent.com/378699/47686422-0a008e80-dc16-11e8-99ab-f9ecc1186b1a.png)

Even I use description part, after export, I found it is just a link, is not a displayed image. Like this:

![image](https://user-images.githubusercontent.com/378699/47687496-7336d080-dc1b-11e8-9708-c0ea1f072f6d.png)

org version: 9.1.14
emacs version: 26.1
platform: Arch Linux, 4.18.16
installed via: MELPA

**Comment by ofosos** [comment]
Can you try
```
#+ATTR_ORG: :width 600
#+ATTR_LATEX: :width 6.0in
#+ATTR_HTML: :width 600px
[[file:data/4f/19eb7e-a943-477c-835b-d7df100e19ca/Clojure%20type%20selection%20flowchart.png][test]]
```

This should still work, but if you append much more characters, you maybe running out of space to describe the file. I think files on HFS+ should be limited to a max path length of 255 characters, this is already at 225 characters.

**Comment by ofosos** [comment]
Please also provide an `ls -` of the directory the image sits in.

**Comment by stardiviner** [comment]
Here is the result of command `ls` of that directory:
```org
#+begin_src sh
ls data/4f/19eb7e-a943-477c-835b-d7df100e19ca/
#+end_src

#+RESULTS[<2018-10-30 13:56:27> e3c846a5aad60fb23050a8b9476eab4031c1778d]:
: Clojure type selection flowchart.png
```

**Comment by stardiviner** [comment]
I always use `org-attach` to add image into attachments, and link the attached image file to insert inline image.

**Comment by stardiviner** [comment]
> Can you try
> 
> ```
> #+ATTR_ORG: :width 600
> #+ATTR_LATEX: :width 6.0in
> #+ATTR_HTML: :width 600px
> [[file:data/4f/19eb7e-a943-477c-835b-d7df100e19ca/Clojure type selection flowchart.png][test]]
> ```
> 
> This should still work, but if you append much more characters, you maybe running out of space to describe the file. I think files on Linux should be limited to a max path length of 255 characters, this is already at 225 characters.

From the error output:
`file-missing Opening input file No such file or directory /home/stardiviner/Org/Wiki/Computer Technology/Programming/Programming Languages/Clojure/Data/Manuals/My Clojure Language Syntax Reference/data/4f/19eb7e-a943-477c-835b-d7df100e19ca/Clojure%20type%20selection%20flowchart.png)`

I think its because Org interept the single space in filename into `%20`, but when create EPUB image link, Org Mode or ox-epub can't interept it back to single space (which is the real path).

**Comment by ofosos** [comment]
Can you try the code from the branch `unescape-link`? This might work.

**Comment by stardiviner** [comment]
It works for links without `desc` in `[[link][desc]]` after wrap with `org-link-unescape`. Can it support those inline image links has `desc` ?

**Comment by ofosos** [comment]
I pushed another change, can you test again?

**Comment by ofosos** [comment]
I don't think this change will do what you want to do. It is however correct. Creating `[[foo.png][image foo]]` is an external link in org mode, it is not an inline image.

If you want an inline image with a description use
```
#+CAPTION: A black cat stalking a spider
[[./img/a.jpg]]
```

See: https://orgmode.org/manual/Images-in-HTML-export.html

**Comment by stardiviner** [comment]
I see, I might consider to improve org-insert-link to auto detect file is an image or not, so that will decide whether insert `[desc]` part.
Thanks @ofosos

**Comment by ofosos** [comment]
I'm going to merge the changes to support whitespace in the evening. Currently I have a broken magit installation. Thank you for your help weeding out the bugs!

**Comment by ofosos** [comment]
Changes are on master and will be in the next stable release.

**Comment by stardiviner** [comment]
Thanks for update in master. I have got it in MELPA.
