### ISSUE TITLE
How can I export without a footer

### ISSUE THREAD

**Issue by mrbig033** [ofosos/ox-epub#28]
#### Runtime Environment

- MX Linux 17
- GNU Emacs 27.0.50
- Evil version 1.2.14
- [.emacs.d](https://github.com/mrbig033/dotfiles/tree/master/emacs/emacs_default)
- [packages](https://github.com/mrbig033/dotfiles/blob/master/emacs/emacs_default/packs.el)
- Org Version: 9.1.9
- MELPA

#### Issue

How can I export without a footer, such as:

```
Author: Robert A. Heinlein
Created: 2019-02-28 Thu 00:51
Validate
```

**Comment by ofosos** [comment]
Try to evaluate the following:

```
(setq org-export-html-postamble nil)
```

**Comment by mrbig033** [comment]
This doesn't work for some reason, but that does:

`#+OPTIONS: html-postamble:nil`

**Comment by ofosos** [comment]
Cool :+1:
