### ISSUE TITLE
How to set the title image

### ISSUE THREAD

**Issue by mrbig033** [ofosos/ox-epub#30]
### Runtime Environment

- Org mode version 9.2.3
- GNU Emacs 27.0.50
- MX Linux 18
- Installed via Melpa
- ox-epub 20181101.1854
- [dotfiles](https://github.com/mrbig033/dotfiles)
- [~/.emacs.d](https://github.com/mrbig033/Emacs)

### Issue

The readme mentions it is possible to add a cover image, but there's no mention how. The sample don't seem to have one. Could you please help me achieve this? Thanks!

**Comment by ofosos** [comment]
Try setting a header variable named `EPUBCOVER` like so:

```
#+AUTHOR: Mark Meyer
#+EPUBCOVER: cover.png
```

**Comment by mrbig033** [comment]
That works fine. Is this in the documentation? Thanks!

**Comment by ofosos** [comment]
Do you think the mention in the README is ok?
