### ISSUE TITLE
Can you get syntax highlighting in epub?

### ISSUE THREAD

**Issue by jkitchin** [ofosos/ox-epub#34]
If I export an org file with src blocks in it, the blocks are not syntax fontified in the resulting epub.  Is this something that needs to be added via CSS or some other means? The same document looks great in html.

org version: 9.5
emacs version: 28
platform: Mac
installed via: MELPA

**Comment by ofosos** [comment]
IIRC it took some effort to diable it. For my use case it was detrimental, because I use a b/w e-ink display.

**Comment by jkitchin** [comment]
It seems to be dependent on the viewer I guess. If I view the epub in calibre, the code is syntax highlighted, but in the Mac Books viewer it is not. I guess we can close this.
