### ISSUE TITLE
keywords

### ISSUE THREAD

**Issue by pank** [ofosos/ox-epub#4]
Hi,

It would seem that something like `uid` should be a keyword.  So that I can write something like

     #+uid: 12345

in my org file.  In fact, all of these should probably be proper keywords.  

    uid subject publisher rights manifest spine cover

I don't know what `spine` and `manifest` are.  These should be added to `org-export-define-derived-backend`.  See e.g. [here](http://orgmode.org/cgit.cgi/org-mode.git/tree/contrib/lisp/ox-koma-letter.el?id=6341de0117c84a6d148333a7269c1e6d910f3fc3#n424).

**Comment by ofosos** [comment]
Spine is the order of included html files, while manifest is a list of files included in the epub.

I agree with you on this.

**Comment by pank** [comment]
Mark Meyer <notifications@github.com> writes:

> Spine is the order of included html files, while manifest is a list of files included in the epub.

So I guess both ‘spine’ and ‘manifest’ could and should be deduced from
the target Org file, right?

**Comment by ofosos** [comment]
With manifest yes, with spine not necessarily. With the current structure (multiple org files make one epub) you should be able to define the spine manually.

**Comment by ofosos** [comment]
Start this work, plan for tomorrow: org-epub-publish-finish extracts a lot of these values from the project plist, these are then passed as explicit named arguments to the subordinate functions. These should be left in a plist and the plist should be passed to the subordinate functions for them to extract it. This will slim down org-epub-publish-finish, getting us in the right direction.

**Comment by pank** [comment]
Right, basically all backend specific keywords should be moved to `org-export-define-derived-backend`.

So, you should have something like 



    ;; See docstrig of `org-export-define-derived-backend'
    (org-export-define-derived-backend 'koma-letter 'latex
      :options-alist
      ;; See docstring of `org-export-options-alist'
      '((:epub-uid "UID" nil nil t)
        ;; ...
        )
      :translate-alist
      '((template . org-epub-template))
      :menu-entry
      '(?E "Export to Epub"
           ((?e "As Epub file" org-epub-export-to-epub)
            (?O "As ODT file and open"
                (lambda (a s v b)
                  (if a (org-odt-export-to-epub t s v)
                    (org-open-file (org-odt-export-to-epub nil s v) 'system)))))))

**Comment by ofosos** [comment]
This should now work on master C-c C-e E e will export the current buffer to epub and place an appropriately named epub in your source folder. Please try it.

There's still some usage of file-base-name and such, hence the version bump to Emacs 24.3.

The publish functions are currently broken on master (no cache), I'll consider if I can get them in a working state tomorrow.

**Comment by ofosos** [comment]
From my point of view the keywords are now properly implemented. I will cross-check the available properties and their implementation and then document their function and syntax in README.org and close this bug.

**Comment by ofosos** [comment]
Clarified keyword syntax in docs.
