### ISSUE TITLE
Provide basic CSS

### ISSUE THREAD

**Issue by ofosos** [ofosos/ox-epub#7]
At present all CSS definitions are stripped from the ox-html backend. EPUB doesn't support inline CSS (<style>), but you can include a limited subset of CSS via an external stylesheet. Do this. Provide reasonable defaults that fit org-mode well.

**Comment by pank** [comment]
Couldn't you use the default style or would they not work for `epub`?

    (with-temp-file "/tmp/book-style.css"
      (save-excursion (insert org-html-style-default))
      ;; Delete the upper part.
      (delete-region (point-min)
                     (progn (search-forward-regexp "[ \t]*\\.[a-zA-Z]+[ \t]*{")
                            (point-at-bol)))
      (goto-char (point-max))
      (delete-region (1+ (search-backward "}")) (point-max)))

**Comment by ofosos** [comment]
I would like to have a page break before each h1 element. I'm looking into this. But this should not prevent implementation of a mechanism to include neither a user provided nor a default stylesheet.

**Comment by pank** [comment]
For at least printing, there's some css property for page breaks ([ref](https://www.w3schools.com/cssref/pr_print_pagebb.asp)).  I don't know if it works for epub, but it seems it should.

Is there a reason why you define `org-epub-style-default` as oppose to use `org-html-style-default`?  As you anyway need `ox-html` it might make it harder to maintain.  But perhaps over time it will be worth it to separate them.

**Comment by ofosos** [comment]
See the commit message:

We use our own style, instead of the default style from ox-html,
because the EPUB specification actually subsets CSS and doesn't for
example allow absolute positioning in the included CSS, which is
present in the ox-html default style.

**Comment by pank** [comment]
I see.  that makes sense.

Some additional thoughts, looking at the commit. 

You might want to check `:html-head-include-default-style` before inserting styles, in case someone wants to use an independent stylesheet or something equivalent.  Also, perhaps `#+html_head{_extra}` is enough to add additional styles.  Or the names could be `#+epub_head{_extra}`.

Also, shouldn't `#+epubstyle` support a list of files?  So I can say something like,

    #+epubstyle: larger-h1.css centered-tables.css ...

See e.g. `#+lco` in `ox-koma-letter.el`.

**Comment by ofosos** [comment]
The way this is done currently is, that EPUBSTYLE overwrites the default style sheet. But actually using it as an additional stylesheet and then enabling exclusion of the default via `:html-head-include-default-style` is a good idea.

Both `#+html_head{_extra}` and `#+epub_head{_extra}` aren't a supported way to do this. EPUB doesn't allow inline definition of styles, hence the external stylesheet.

**Comment by pank** [comment]
Okay, then it makes sense to only have a list of style sheets to include.
As long as you are not using (org-html--build-head info) they will anyway
be ignored.

**Comment by ofosos** [comment]
Ok, this should be done.
