### ISSUE TITLE
a perspective on TOCs

### ISSUE THREAD

**Issue by pank** [ofosos/ox-epub#9]
hi,

I'm just reading parts of your code some of the time and I obviously don't know it as well as you.  So please ignore ill-founded comments.

It seems you are collecting headlines to create the TOCs in `org-epub-template`.  

First, couldn't you get your `headlines` as,

    (org-element-map (plist-get info :parse-tree) 'headline
      (lambda (h)
        (list (org-element-property :raw-value h)
              org-epub-current-file
              (org-element-property :level h)
              (org-export-get-reference h info))))

You might even be able to do something like this, if that suits your style,

    (org-element-map (plist-get info :parse-tree) 'headline
      (lambda (h)
        (org-element-put-property h :filename org-epub-current-file)))

Second, are there technical/'traditional' reasons for not having the whole epub text in a single html file?  If not, it might make accounting easier if everything is in a single file, at least in terms of generating TOCs. 

Thirdly, you might find that it is easier to keep a collection of headline elements and filename associations.  Then you can call `org-element-property` on the element as needed later.  It might make it possible to shorten `org-epub-generate-toc-single`.

**Comment by ofosos** [comment]
I think this is mostly implemented. It's a good idea, more aligned towards the api and not the concrete structure of the data. I think the second part is no longer needed. Can I close this issue?

Much appreciated.
